# Generated by Django 5.2.4 on 2025-07-13 20:59

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="Дата платежа"
            ),
        ),
    ]
