# Generated by Django 5.2.4 on 2025-07-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_payment_payment_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="stripe_payment_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="ID платежа в Stripe",
            ),
        ),
    ]
