# Generated by Django 5.2.4 on 2025-07-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_payment_stripe_payment_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="link_payment",
            field=models.URLField(
                blank=True, max_length=400, null=True, verbose_name="Ссылка на оплату"
            ),
        ),
    ]
