# Используем официальный slim-образ Python 3.12
FROM python:3.12-slim


# Устанавливаем рабочую директорию в контейнере
WORKDIR /app

# Устанавливаем зависимости системы
RUN apt-get update && \
    apt-get install -y \
        curl\
        gcc \
        libpq-dev \
    && apt-get clean

# Копируем файл зависимостей в контейнер
COPY requirements.txt ./

# Устанавливаем зависимости Python
RUN pip install --no-cache-dir -r requirements.txt


# Копируем файл README.md в контейнер
COPY README.md ./

# Копируем исходный код приложения в контейнер
COPY . .

# Создаем директорию для медиафайлов
RUN mkdir -p /config/media

# Пробрасываем порт, который будет использовать Django
EXPOSE 8000

# Команда для запуска Celery работника
CMD ["celery", "-A", "config", "worker", "-l", "info", "-P", "solo"]