# Generated by Django 5.2.4 on 2025-07-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0006_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Цена в Stripe"
            ),
        ),
    ]
